# Generated by Django 5.2.3 on 2025-06-18 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='聯賽名稱')),
                ('season', models.CharField(max_length=20, verbose_name='賽季')),
                ('group', models.CharField(choices=[('幼兒組', '幼兒組'), ('國小組', '國小組'), ('國中組', '國中組'), ('高中組', '高中組'), ('成人組', '成人組')], max_length=50, verbose_name='組別')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '聯賽',
                'verbose_name_plural': '聯賽',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='球隊名稱')),
                ('group', models.CharField(choices=[('幼兒組', '幼兒組'), ('國小組', '國小組'), ('國中組', '國中組'), ('高中組', '高中組'), ('成人組', '成人組')], max_length=50, verbose_name='組別')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('coach', models.ForeignKey(limit_choices_to={'user_type': 'coach'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='教練')),
            ],
            options={
                'verbose_name': '球隊',
                'verbose_name_plural': '球隊',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.IntegerField(verbose_name='球衣號碼')),
                ('position', models.CharField(choices=[('GK', '守門員'), ('DF', '後衛'), ('MF', '中場'), ('FW', '前鋒')], max_length=20, verbose_name='位置')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='身高(cm)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='體重(kg)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('is_injured', models.BooleanField(default=False, verbose_name='是否受傷')),
                ('injury_description', models.TextField(blank=True, null=True, verbose_name='傷勢描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.team', verbose_name='球隊')),
            ],
            options={
                'verbose_name': '球員',
                'verbose_name_plural': '球員',
                'unique_together': {('team', 'jersey_number')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(verbose_name='比賽時間')),
                ('venue', models.CharField(max_length=200, verbose_name='比賽場地')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='主隊得分')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='客隊得分')),
                ('status', models.CharField(choices=[('scheduled', '已安排'), ('in_progress', '進行中'), ('finished', '已結束'), ('cancelled', '已取消')], default='scheduled', max_length=20, verbose_name='比賽狀態')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.league', verbose_name='聯賽')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='team_management.team', verbose_name='客隊')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='team_management.team', verbose_name='主隊')),
            ],
            options={
                'verbose_name': '比賽',
                'verbose_name_plural': '比賽',
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0, verbose_name='進球數')),
                ('assists', models.IntegerField(default=0, verbose_name='助攻數')),
                ('yellow_cards', models.IntegerField(default=0, verbose_name='黃牌數')),
                ('red_cards', models.IntegerField(default=0, verbose_name='紅牌數')),
                ('minutes_played', models.IntegerField(default=0, verbose_name='出場時間(分鐘)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.match', verbose_name='比賽')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.player', verbose_name='球員')),
            ],
            options={
                'verbose_name': '球員統計',
                'verbose_name_plural': '球員統計',
                'unique_together': {('player', 'match')},
            },
        ),
    ]
