# Generated by Django 5.2.3 on 2025-06-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='injury_description',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_injured',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=20, verbose_name='年齡'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='球員', max_length=50, verbose_name='球員暱稱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.CharField(default='MF', help_text='可選擇多個位置，以逗號分隔', max_length=100, verbose_name='位置'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='speed',
            field=models.CharField(choices=[('優', '優'), ('佳', '佳'), ('普', '普')], default='佳', max_length=10, verbose_name='速度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='stamina',
            field=models.CharField(choices=[('優', '優'), ('佳', '佳'), ('普', '普')], default='佳', max_length=10, verbose_name='體力'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='technique',
            field=models.CharField(choices=[('優', '優'), ('佳', '佳'), ('普', '普')], default='佳', max_length=10, verbose_name='技術'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='球衣號碼'),
        ),
    ]
