# Generated by Django 5.2.3 on 2025-06-18 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0003_league_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_name',
            field=models.CharField(default='', max_length=100, verbose_name='對手名稱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='對手得分'),
        ),
        migrations.AddField(
            model_name='match',
            name='our_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='我方得分'),
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team_management.team', verbose_name='我方球隊'),
            preserve_default=False,
        ),
    ]
