# Generated by Django 5.2.3 on 2025-06-18 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0004_remove_match_away_score_remove_match_away_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_participating', models.BooleanField(default=False, verbose_name='是否參加')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.match', verbose_name='比賽')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.player', verbose_name='球員')),
            ],
            options={
                'verbose_name': '球員參加比賽',
                'verbose_name_plural': '球員參加比賽',
                'unique_together': {('player', 'match')},
            },
        ),
    ]
