# Generated by Django 5.2.3 on 2025-06-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0005_playermatchparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leagues',
            field=models.ManyToManyField(blank=True, related_name='participating_teams', to='team_management.league', verbose_name='參加聯賽'),
        ),
    ]
