# Generated by Django 4.2.7 on 2025-06-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0006_team_leagues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', '已安排'), ('in_progress', '確認中'), ('finished', '已結束'), ('cancelled', '已取消'), ('postponed', '已延期')], default='scheduled', max_length=20, verbose_name='比賽狀態'),
        ),
        migrations.AlterField(
            model_name='playermatchparticipation',
            name='is_participating',
            field=models.BooleanField(default=True, verbose_name='是否參加'),
        ),
    ]
